---
- name: install pip
  package:
    name: python-pip
    state: present
- name: install git
  package:
    name: git
    state: present
- name: install docker-py
  pip: 
    name: docker-py 
    state: latest
- name: install docker-py
  pip:
    name: docker-compose
    state: latest

